# A list of devices you want to take the screenshots from
devices([
  "iPhone 6",
  "iPhone 6 Plus",
  "iPhone 5",
  "iPad Air",
  "iPad Pro",
  "iPad Retina"
])

languages([
  "en-US",
  "en-GB"
])

# The name of the scheme which contains the UI Tests
scheme "Spark"

# Where should the resulting screenshots be stored?
output_directory "./fastlane/screenshots"

clear_previous_screenshots true # remove the '#' to clear all previously generated screenshots before creating new ones

# Choose which project/workspace to use
project "./Spark.xcodeproj"
